FROM stefco:/llama:datagrid

COPY . /user/llama/provision  # copies all requirements and docker files

# install git-lfs and conda
RUN su llama --login --shell bash --command ' \
    cd ~
    git lfs install \
    conda env create -f ~/provision/llama-py36.yml \
        && echo "conda activate llama-py36" >>~/.bashrc \
        && cat ~/.bashrc \
        && source ~/.bashrc \
        && pip install -r ~/provision/requirements.txt \
        && rm ~/provision
'
# install pip requirements and delete copied files
# RUN bash -i -c 'pip install -r ~/provision/requirements.txt && rm -r ~/provision'

# ENV PATH /home/llama/miniconda3/bin:"$PATH"

# Change owner to 'llama'
# TODO fix this; it is very slow and seems obviously wrong. must be another way
# to set ownership to llama...
# RUN chown -R llama:llama /home/llama
# RUN bash -i -c "python setup.py develop"
        # llama --help; \
        # make test; \

# Make port 80 available to the world outside this container
# EXPOSE 80gg

# Run app.py when the container launches
# CMD ["python", "app.py"]
