# For building and uploading conda packages and environments
FROM stefco/llama-env:py37-0.0.10

COPY requirements-dev.txt /home/llama/requirements-dev.txt
RUN su llama -c 'bash -i -c " \
        conda install anaconda-client conda-build \
            && pip install -r /home/llama/requirements-dev.txt \
    "' \
    && rm /home/llama/requirements-dev.txt
