FROM stefco/llama-base:alpine

COPY . /home/llama/provision

# install git-lfs and conda
RUN su llama -c "bash -i -c ' \
    cd ~ \
        && type conda \
        && conda env create -f ~/provision/llama-py37.yml \
        && echo conda\ activate\ llama-py37\ >>~/.bashrc \
        && cat ~/.bashrc \
        && source ~/.bashrc \
        && pip install -r ~/provision/requirements.txt \
        && rm -r ~/miniconda3/pkgs \
'" \
    && apk --no-cache add graphviz font-bitstream-type1 \
    && rm -rf /home/llama/provision
USER llama
WORKDIR /home/llama
