FROM stefco:/llama:datagrid

COPY . /user/llama/provision  # copies all requirements and docker files

# install git-lfs and conda
RUN su llama --login --shell bash --command ' \
    cd ~
    git lfs install \
    curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
        && Miniconda3-latest-Linux-x86_64.sh -b -f -p /home/llama/miniconda3 \
        && rm Miniconda3-latest-Linux-x86_64.sh \
        && /home/llama/miniconda3/bin/conda update conda \
        && /home/llama/miniconda3/bin/conda update --all \
        && /home/llama/miniconda3/bin/conda config --add channels conda-forge \
        && /home/llama/miniconda3/bin/conda config --add channels conda-forge \
        && /home/llama/miniconda3/bin/conda env create -f ~/provision/llama-py37.yml \
        && /home/llama/miniconda3/bin/conda init bash \
        && echo "conda activate llama-py37" >>~/.bashrc \
        && cat ~/.bashrc \
'
# install pip requirements and delete copied files
RUN bash -i -c 'pip install -r ~/provision/requirements.txt && rm -r ~/provision'

# ENV PATH /home/llama/miniconda3/bin:"$PATH"

# Change owner to 'llama'
# TODO fix this; it is very slow and seems obviously wrong. must be another way
# to set ownership to llama...
# RUN chown -R llama:llama /home/llama
# RUN bash -i -c "python setup.py develop"
        # llama --help; \
        # make test; \

# Make port 80 available to the world outside this container
# EXPOSE 80gg

# Run app.py when the container launches
# CMD ["python", "app.py"]
