#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

REPO="$(awk -F'/' '{print $(NF-1) "/" $NF}' <<<"${DOCKER_REPO}")"
NAME="${REPO}:${DOCKER_TAG}"

docker build \
    --build-arg NAME="${NAME}" \
    --build-arg VERSION="$(git describe --tags --always)" \
    --build-arg COMMIT="$(git rev-parse HEAD)" \
    --build-arg URL="$(git config --get remote.origin.url)" \
    --build-arg BRANCH="$(git rev-parse --abbrev-ref HEAD)" \
    --build-arg DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg REPO="${REPO}" \
    --build-arg DOCKER_TAG="${DOCKER_TAG}" \
    --build-arg DOCKERFILE_PATH="${DOCKERFILE_PATH}" \
    --file "${DOCKERFILE_PATH}" \
    "$@" \
    -t ${NAME} .
