#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

REPO="$(awk -F'/' '{print $(NF-1) "/" $NF}' <<<"${DOCKER_REPO}")"
NAME="${REPO}:${DOCKER_TAG}"
DOCKER_META="- version: $(git describe --tags --always)
  commit: $(git rev-parse HEAD)
  url: $(git config --get remote.origin.url)
  branch: $(git rev-parse --abbrev-ref HEAD)
  date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  docker_repo: ${REPO}
  docker_tag: ${DOCKER_TAG}
  image_name: ${NAME}
  dockerfile_path: ${DOCKERFILE_PATH}
  dockerfile: |
$(sed 's/^/    /' <${DOCKERFILE_PATH})
"

printf "DOCKER_META:\n%s" "${DOCKER_META}"

docker build \
    --build-arg "${DOCKER_META}" \
    --file "${DOCKERFILE_PATH}" \
    -t ${NAME} .
